/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Marketplace configuration for Claude Code
 */
export interface ClaudeCodeMarketplace {
  /**
   * Marketplace name
   */
  name: string;
  owner: {
    name: string;
    email: string;
  };
  plugins: {
    name: string;
    /**
     * Relative path to plugin directory
     */
    source: string;
  }[];
}
