/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Marketplace configuration file for curated plugin output
 */
export interface MarketplaceConfiguration {
  /**
   * Marketplace name
   */
  name: string;
  /**
   * Marketplace owner information
   */
  owner: {
    name: string;
    email?: string;
  };
  /**
   * List of plugins in this marketplace
   */
  plugins: {
    /**
     * Plugin name
     */
    name: string;
    /**
     * Relative path to plugin directory
     */
    source: string;
  }[];
}
