/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for the curator's internal normalized plugin format
 */
export interface NormalizedPluginConfiguration {
  /**
   * Plugin name (always present)
   */
  name: string;
  /**
   * Absolute path to plugin directory
   */
  source: string;
  /**
   * Plugin version
   */
  version: string;
  /**
   * Plugin description
   */
  description: string;
  /**
   * Plugin author information
   */
  author: {
    name: string;
    email: string;
    url: string;
  };
  /**
   * Plugin homepage URL
   */
  homepage: string;
  /**
   * Plugin repository URL
   */
  repository: string;
  /**
   * Plugin license
   */
  license: string;
  /**
   * Plugin keywords
   */
  keywords: string[];
  /**
   * Array of command file paths (always array, never undefined)
   */
  commands: string[];
  /**
   * Array of agent file paths (always array, never undefined)
   */
  agents: string[];
  /**
   * Array of skill directory paths (always array, never undefined)
   */
  skills: string[];
  /**
   * Array of hook configurations (always array, never undefined)
   */
  hooks: {
    /**
     * Hook event name (PreToolUse, PostToolUse, UserPromptSubmit, etc.)
     */
    event: string;
    /**
     * Hook type (currently only 'command' is supported)
     */
    type: "command";
    /**
     * Command path (may reference ${CLAUDE_PLUGIN_ROOT})
     */
    command: string;
    /**
     * Optional tool matcher pattern
     */
    matcher?: string;
    /**
     * Optional timeout in seconds
     */
    timeout?: number;
    [k: string]: unknown;
  }[];
  /**
   * Array of MCP server configurations (always array, never undefined)
   */
  mcps: {
    /**
     * MCP server name (extracted from mcpServers key)
     */
    name: string;
    /**
     * Executable command
     */
    command: string;
    /**
     * Optional command arguments
     */
    args?: string[];
    /**
     * Optional environment variables
     */
    env?: {
      [k: string]: string;
    };
    [k: string]: unknown;
  }[];
}
