/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Internal normalized plugin format used by curator
 */
export interface NormalizedPlugin {
  /**
   * Plugin name
   */
  name: string;
  /**
   * Absolute path to plugin directory
   */
  source: string;
  /**
   * Semantic version (default: 0.0.0)
   */
  version: string;
  /**
   * Plugin description (default: empty string)
   */
  description: string;
  /**
   * Author info (default: all empty strings)
   */
  author: {
    name: string;
    email: string;
    url: string;
    [k: string]: unknown;
  };
  /**
   * Homepage URL (default: empty string)
   */
  homepage: string;
  /**
   * Repository URL (default: empty string)
   */
  repository: string;
  /**
   * License (default: empty string)
   */
  license: string;
  /**
   * Keywords (default: empty array)
   */
  keywords: string[];
  /**
   * Command file paths (relative, always array)
   */
  commands: string[];
  /**
   * Agent file paths (relative, always array)
   */
  agents: string[];
  /**
   * Skill directory paths (relative, always array)
   */
  skills: string[];
  /**
   * Hooks (flat array, always array)
   */
  hooks: {
    /**
     * Hook event name
     */
    event: string;
    /**
     * Hook type (only command supported)
     */
    type: "command";
    /**
     * Command to execute
     */
    command: string;
    /**
     * Optional matcher pattern
     */
    matcher?: string;
    /**
     * Optional timeout in seconds
     */
    timeout?: number;
    [k: string]: unknown;
  }[];
  /**
   * MCP servers (flat array, always array)
   */
  mcps: {
    /**
     * MCP server name
     */
    name: string;
    /**
     * Executable command
     */
    command: string;
    /**
     * Command arguments
     */
    args?: string[];
    /**
     * Environment variables
     */
    env?: {
      [k: string]: string;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
