/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Internal normalized format used by the curator TUI
 */
export interface NormalizedPluginInternalFormat {
  /**
   * Plugin name (always present)
   */
  name: string;
  /**
   * Absolute path to plugin directory
   */
  source: string;
  /**
   * Semantic version (default: 0.0.0)
   */
  version: string;
  /**
   * Brief description (default: empty string)
   */
  description: string;
  author: {
    name: string;
    email: string;
    url: string;
  };
  /**
   * Homepage URL (default: empty string)
   */
  homepage: string;
  /**
   * Repository URL (default: empty string)
   */
  repository: string;
  /**
   * License identifier (default: empty string)
   */
  license: string;
  /**
   * Keywords array (default: empty array)
   */
  keywords: string[];
  /**
   * Array of command file paths (relative to plugin root)
   */
  commands: string[];
  /**
   * Array of agent file paths (relative to plugin root)
   */
  agents: string[];
  /**
   * Array of skill directory paths (relative to plugin root)
   */
  skills: string[];
  /**
   * Array of hooks (flat structure)
   */
  hooks: {
    /**
     * Hook event name
     */
    event: string;
    type: "command";
    /**
     * Command to execute
     */
    command: string;
    /**
     * Tool matcher pattern (optional)
     */
    matcher?: string;
    /**
     * Timeout in seconds (optional)
     */
    timeout?: number;
    [k: string]: unknown;
  }[];
  /**
   * Array of MCP servers (flat structure)
   */
  mcps: {
    /**
     * MCP server name
     */
    name: string;
    /**
     * Executable command
     */
    command: string;
    /**
     * Command arguments
     */
    args?: string[];
    /**
     * Environment variables
     */
    env?: {
      [k: string]: string;
    };
    [k: string]: unknown;
  }[];
}
