/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Official Claude Code plugin format (.claude-plugin/plugin.json)
 */
export interface PluginJson {
  /**
   * Plugin name (kebab-case)
   */
  name?: string;
  /**
   * Semantic version
   */
  version?: string;
  /**
   * Plugin description
   */
  description?: string;
  author?: {
    name?: string;
    email?: string;
    url?: string;
    [k: string]: unknown;
  };
  /**
   * Documentation URL
   */
  homepage?: string;
  /**
   * Source code URL
   */
  repository?: string;
  /**
   * License identifier
   */
  license?: string;
  /**
   * Search keywords
   */
  keywords?: string[];
  /**
   * Command files/directories
   */
  commands?: string | string[];
  /**
   * Agent files/directories
   */
  agents?: string | string[];
  /**
   * Skill directories
   */
  skills?: string | string[];
  /**
   * Hooks configuration (file path or inline config)
   */
  hooks?:
    | string
    | {
        [k: string]: unknown;
      };
  /**
   * MCP servers configuration (file path or inline config)
   */
  mcpServers?:
    | string
    | {
        [k: string]: unknown;
      };
  [k: string]: unknown;
}
