/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Official Claude Code plugin.json format
 */
export interface ClaudeCodePlugin {
  /**
   * Plugin name in kebab-case format
   */
  name?: string;
  /**
   * Semantic version
   */
  version?: string;
  /**
   * Brief explanation of plugin purpose
   */
  description?: string;
  author?: {
    name?: string;
    email?: string;
    url?: string;
    [k: string]: unknown;
  };
  /**
   * Documentation URL
   */
  homepage?: string;
  /**
   * Source code repository URL
   */
  repository?: string;
  /**
   * License identifier (e.g., MIT, Apache-2.0)
   */
  license?: string;
  /**
   * Discovery tags
   */
  keywords?: string[];
  /**
   * Custom command paths (string glob or array of paths)
   */
  commands?: string | string[];
  /**
   * Custom agent paths
   */
  agents?: string | string[];
  /**
   * Hook configuration file path or inline config
   */
  hooks?:
    | string
    | {
        [k: string]: unknown;
      };
  /**
   * MCP server configuration file path or inline config
   */
  mcpServers?:
    | string
    | {
        [k: string]: unknown;
      };
}
