/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Official plugin.json format for Claude Code plugins
 */
export interface ClaudeCodePluginOfficialFormat {
  /**
   * Plugin name (kebab-case format)
   */
  name?: string;
  /**
   * Semantic version
   */
  version?: string;
  /**
   * Brief explanation of the plugin's purpose
   */
  description?: string;
  author?: {
    name?: string;
    email?: string;
    url?: string;
    [k: string]: unknown;
  };
  /**
   * URL of documentation
   */
  homepage?: string;
  /**
   * URL of source code
   */
  repository?: string;
  /**
   * License identifier
   */
  license?: string;
  /**
   * Discovery tags
   */
  keywords?: string[];
  /**
   * Command files or directories
   */
  commands?: string | string[];
  /**
   * Agent files or directories
   */
  agents?: string | string[];
  /**
   * Skill directories
   */
  skills?: string | string[];
  /**
   * Hook configuration file path or inline configuration
   */
  hooks?:
    | string
    | {
        [k: string]: unknown;
      };
  /**
   * MCP servers configuration file path or inline configuration
   */
  mcpServers?:
    | string
    | {
        [k: string]: unknown;
      };
  [k: string]: unknown;
}
